In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'col_1' : [1, 2, 3, 4, 5, 6, 7, 8]})
df

col_1
0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8

# Digitize

Used when bins' edges are specified

In [3]:
np.digitize(df['col_1'], [2,4,7], right=False)

array([0, 1, 1, 2, 2, 2, 3, 3], dtype=int64)

In [4]:
np.digitize(df['col_1'], [2,4,7], right=True)

array([0, 0, 1, 1, 2, 2, 2, 3], dtype=int64)

In [5]:
np.digitize(df['col_1'], [7,4,2], right=False)

array([3, 2, 2, 1, 1, 1, 0, 0], dtype=int64)

In [6]:
np.digitize(df['col_1'], [7,4,2], right=True)

array([3, 3, 2, 2, 1, 1, 1, 0], dtype=int64)

# Binned Statistic 

Used when number of bins is specified

https://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.stats.binned_statistic.html

In [7]:
from scipy.stats import binned_statistic

In [8]:
binned = binned_statistic(df['col_1'], df['col_1'], bins=3, range=(2, 6), statistic='mean')

Binning happena only on values withing "range"

values outside of the "range" are assigned to other bins

In [9]:
print('Bin assignation:\t', binned.binnumber)

Bin assignation:	 [0 1 1 2 3 3 4 4]


In [10]:
print('Within-bin statistic:\t', binned.statistic)

Within-bin statistic:	 [2.5 4.  5.5]


In [11]:
print('Bin Edges:\t', binned.bin_edges)

Bin Edges:	 [2.         3.33333333 4.66666667 6.        ]
